// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Data.proto

package com.ilmservice.personalbudget.protobufs;

public final class Data {
  private Data() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TransactionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ilmservice.personalbudget.Transaction)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional bytes id = 1;</code>
     */
    com.google.protobuf.ByteString getId();

    /**
     * <code>optional uint32 categoryId = 2;</code>
     */
    boolean hasCategoryId();
    /**
     * <code>optional uint32 categoryId = 2;</code>
     */
    int getCategoryId();

    /**
     * <code>repeated uint32 tagIds = 3;</code>
     */
    java.util.List<java.lang.Integer> getTagIdsList();
    /**
     * <code>repeated uint32 tagIds = 3;</code>
     */
    int getTagIdsCount();
    /**
     * <code>repeated uint32 tagIds = 3;</code>
     */
    int getTagIds(int index);

    /**
     * <code>optional uint32 userId = 4;</code>
     */
    boolean hasUserId();
    /**
     * <code>optional uint32 userId = 4;</code>
     */
    int getUserId();

    /**
     * <code>optional uint64 date = 5;</code>
     */
    boolean hasDate();
    /**
     * <code>optional uint64 date = 5;</code>
     */
    long getDate();

    /**
     * <code>optional sint32 cents = 6;</code>
     */
    boolean hasCents();
    /**
     * <code>optional sint32 cents = 6;</code>
     */
    int getCents();

    /**
     * <code>optional string description = 7;</code>
     */
    boolean hasDescription();
    /**
     * <code>optional string description = 7;</code>
     */
    java.lang.String getDescription();
    /**
     * <code>optional string description = 7;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>optional string card = 8;</code>
     */
    boolean hasCard();
    /**
     * <code>optional string card = 8;</code>
     */
    java.lang.String getCard();
    /**
     * <code>optional string card = 8;</code>
     */
    com.google.protobuf.ByteString
        getCardBytes();
  }
  /**
   * Protobuf type {@code com.ilmservice.personalbudget.Transaction}
   */
  public static final class Transaction extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.ilmservice.personalbudget.Transaction)
      TransactionOrBuilder {
    // Use Transaction.newBuilder() to construct.
    private Transaction(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Transaction(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Transaction defaultInstance;
    public static Transaction getDefaultInstance() {
      return defaultInstance;
    }

    public Transaction getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Transaction(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              categoryId_ = input.readUInt32();
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                tagIds_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              tagIds_.add(input.readUInt32());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                tagIds_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                tagIds_.add(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              userId_ = input.readUInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000008;
              date_ = input.readUInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000010;
              cents_ = input.readSInt32();
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              description_ = bs;
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              card_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          tagIds_ = java.util.Collections.unmodifiableList(tagIds_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ilmservice.personalbudget.protobufs.Data.internal_static_com_ilmservice_personalbudget_Transaction_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ilmservice.personalbudget.protobufs.Data.internal_static_com_ilmservice_personalbudget_Transaction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ilmservice.personalbudget.protobufs.Data.Transaction.class, com.ilmservice.personalbudget.protobufs.Data.Transaction.Builder.class);
    }

    public static com.google.protobuf.Parser<Transaction> PARSER =
        new com.google.protobuf.AbstractParser<Transaction>() {
      public Transaction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Transaction(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Transaction> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString id_;
    /**
     * <code>optional bytes id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes id = 1;</code>
     */
    public com.google.protobuf.ByteString getId() {
      return id_;
    }

    public static final int CATEGORYID_FIELD_NUMBER = 2;
    private int categoryId_;
    /**
     * <code>optional uint32 categoryId = 2;</code>
     */
    public boolean hasCategoryId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint32 categoryId = 2;</code>
     */
    public int getCategoryId() {
      return categoryId_;
    }

    public static final int TAGIDS_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Integer> tagIds_;
    /**
     * <code>repeated uint32 tagIds = 3;</code>
     */
    public java.util.List<java.lang.Integer>
        getTagIdsList() {
      return tagIds_;
    }
    /**
     * <code>repeated uint32 tagIds = 3;</code>
     */
    public int getTagIdsCount() {
      return tagIds_.size();
    }
    /**
     * <code>repeated uint32 tagIds = 3;</code>
     */
    public int getTagIds(int index) {
      return tagIds_.get(index);
    }

    public static final int USERID_FIELD_NUMBER = 4;
    private int userId_;
    /**
     * <code>optional uint32 userId = 4;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional uint32 userId = 4;</code>
     */
    public int getUserId() {
      return userId_;
    }

    public static final int DATE_FIELD_NUMBER = 5;
    private long date_;
    /**
     * <code>optional uint64 date = 5;</code>
     */
    public boolean hasDate() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional uint64 date = 5;</code>
     */
    public long getDate() {
      return date_;
    }

    public static final int CENTS_FIELD_NUMBER = 6;
    private int cents_;
    /**
     * <code>optional sint32 cents = 6;</code>
     */
    public boolean hasCents() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional sint32 cents = 6;</code>
     */
    public int getCents() {
      return cents_;
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 7;
    private java.lang.Object description_;
    /**
     * <code>optional string description = 7;</code>
     */
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string description = 7;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          description_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string description = 7;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CARD_FIELD_NUMBER = 8;
    private java.lang.Object card_;
    /**
     * <code>optional string card = 8;</code>
     */
    public boolean hasCard() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string card = 8;</code>
     */
    public java.lang.String getCard() {
      java.lang.Object ref = card_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          card_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string card = 8;</code>
     */
    public com.google.protobuf.ByteString
        getCardBytes() {
      java.lang.Object ref = card_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        card_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      id_ = com.google.protobuf.ByteString.EMPTY;
      categoryId_ = 0;
      tagIds_ = java.util.Collections.emptyList();
      userId_ = 0;
      date_ = 0L;
      cents_ = 0;
      description_ = "";
      card_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, categoryId_);
      }
      for (int i = 0; i < tagIds_.size(); i++) {
        output.writeUInt32(3, tagIds_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(4, userId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt64(5, date_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeSInt32(6, cents_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(7, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(8, getCardBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, categoryId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < tagIds_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(tagIds_.get(i));
        }
        size += dataSize;
        size += 1 * getTagIdsList().size();
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, userId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, date_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(6, cents_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getDescriptionBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getCardBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.ilmservice.personalbudget.protobufs.Data.Transaction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ilmservice.personalbudget.protobufs.Data.Transaction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ilmservice.personalbudget.protobufs.Data.Transaction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ilmservice.personalbudget.protobufs.Data.Transaction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ilmservice.personalbudget.protobufs.Data.Transaction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ilmservice.personalbudget.protobufs.Data.Transaction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.ilmservice.personalbudget.protobufs.Data.Transaction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.ilmservice.personalbudget.protobufs.Data.Transaction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.ilmservice.personalbudget.protobufs.Data.Transaction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ilmservice.personalbudget.protobufs.Data.Transaction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ilmservice.personalbudget.protobufs.Data.Transaction prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ilmservice.personalbudget.Transaction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ilmservice.personalbudget.Transaction)
        com.ilmservice.personalbudget.protobufs.Data.TransactionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ilmservice.personalbudget.protobufs.Data.internal_static_com_ilmservice_personalbudget_Transaction_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ilmservice.personalbudget.protobufs.Data.internal_static_com_ilmservice_personalbudget_Transaction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ilmservice.personalbudget.protobufs.Data.Transaction.class, com.ilmservice.personalbudget.protobufs.Data.Transaction.Builder.class);
      }

      // Construct using com.ilmservice.personalbudget.protobufs.Data.Transaction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        categoryId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        tagIds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        userId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        date_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        cents_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        card_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ilmservice.personalbudget.protobufs.Data.internal_static_com_ilmservice_personalbudget_Transaction_descriptor;
      }

      public com.ilmservice.personalbudget.protobufs.Data.Transaction getDefaultInstanceForType() {
        return com.ilmservice.personalbudget.protobufs.Data.Transaction.getDefaultInstance();
      }

      public com.ilmservice.personalbudget.protobufs.Data.Transaction build() {
        com.ilmservice.personalbudget.protobufs.Data.Transaction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ilmservice.personalbudget.protobufs.Data.Transaction buildPartial() {
        com.ilmservice.personalbudget.protobufs.Data.Transaction result = new com.ilmservice.personalbudget.protobufs.Data.Transaction(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.categoryId_ = categoryId_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          tagIds_ = java.util.Collections.unmodifiableList(tagIds_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.tagIds_ = tagIds_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.date_ = date_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000010;
        }
        result.cents_ = cents_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000020;
        }
        result.description_ = description_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000040;
        }
        result.card_ = card_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ilmservice.personalbudget.protobufs.Data.Transaction) {
          return mergeFrom((com.ilmservice.personalbudget.protobufs.Data.Transaction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ilmservice.personalbudget.protobufs.Data.Transaction other) {
        if (other == com.ilmservice.personalbudget.protobufs.Data.Transaction.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasCategoryId()) {
          setCategoryId(other.getCategoryId());
        }
        if (!other.tagIds_.isEmpty()) {
          if (tagIds_.isEmpty()) {
            tagIds_ = other.tagIds_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureTagIdsIsMutable();
            tagIds_.addAll(other.tagIds_);
          }
          onChanged();
        }
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasDate()) {
          setDate(other.getDate());
        }
        if (other.hasCents()) {
          setCents(other.getCents());
        }
        if (other.hasDescription()) {
          bitField0_ |= 0x00000040;
          description_ = other.description_;
          onChanged();
        }
        if (other.hasCard()) {
          bitField0_ |= 0x00000080;
          card_ = other.card_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ilmservice.personalbudget.protobufs.Data.Transaction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ilmservice.personalbudget.protobufs.Data.Transaction) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString id_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bytes id = 1;</code>
       */
      public com.google.protobuf.ByteString getId() {
        return id_;
      }
      /**
       * <code>optional bytes id = 1;</code>
       */
      public Builder setId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }

      private int categoryId_ ;
      /**
       * <code>optional uint32 categoryId = 2;</code>
       */
      public boolean hasCategoryId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint32 categoryId = 2;</code>
       */
      public int getCategoryId() {
        return categoryId_;
      }
      /**
       * <code>optional uint32 categoryId = 2;</code>
       */
      public Builder setCategoryId(int value) {
        bitField0_ |= 0x00000002;
        categoryId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 categoryId = 2;</code>
       */
      public Builder clearCategoryId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        categoryId_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> tagIds_ = java.util.Collections.emptyList();
      private void ensureTagIdsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          tagIds_ = new java.util.ArrayList<java.lang.Integer>(tagIds_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated uint32 tagIds = 3;</code>
       */
      public java.util.List<java.lang.Integer>
          getTagIdsList() {
        return java.util.Collections.unmodifiableList(tagIds_);
      }
      /**
       * <code>repeated uint32 tagIds = 3;</code>
       */
      public int getTagIdsCount() {
        return tagIds_.size();
      }
      /**
       * <code>repeated uint32 tagIds = 3;</code>
       */
      public int getTagIds(int index) {
        return tagIds_.get(index);
      }
      /**
       * <code>repeated uint32 tagIds = 3;</code>
       */
      public Builder setTagIds(
          int index, int value) {
        ensureTagIdsIsMutable();
        tagIds_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 tagIds = 3;</code>
       */
      public Builder addTagIds(int value) {
        ensureTagIdsIsMutable();
        tagIds_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 tagIds = 3;</code>
       */
      public Builder addAllTagIds(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureTagIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, tagIds_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 tagIds = 3;</code>
       */
      public Builder clearTagIds() {
        tagIds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      private int userId_ ;
      /**
       * <code>optional uint32 userId = 4;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional uint32 userId = 4;</code>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>optional uint32 userId = 4;</code>
       */
      public Builder setUserId(int value) {
        bitField0_ |= 0x00000008;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 userId = 4;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        userId_ = 0;
        onChanged();
        return this;
      }

      private long date_ ;
      /**
       * <code>optional uint64 date = 5;</code>
       */
      public boolean hasDate() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional uint64 date = 5;</code>
       */
      public long getDate() {
        return date_;
      }
      /**
       * <code>optional uint64 date = 5;</code>
       */
      public Builder setDate(long value) {
        bitField0_ |= 0x00000010;
        date_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 date = 5;</code>
       */
      public Builder clearDate() {
        bitField0_ = (bitField0_ & ~0x00000010);
        date_ = 0L;
        onChanged();
        return this;
      }

      private int cents_ ;
      /**
       * <code>optional sint32 cents = 6;</code>
       */
      public boolean hasCents() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional sint32 cents = 6;</code>
       */
      public int getCents() {
        return cents_;
      }
      /**
       * <code>optional sint32 cents = 6;</code>
       */
      public Builder setCents(int value) {
        bitField0_ |= 0x00000020;
        cents_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional sint32 cents = 6;</code>
       */
      public Builder clearCents() {
        bitField0_ = (bitField0_ & ~0x00000020);
        cents_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>optional string description = 7;</code>
       */
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string description = 7;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            description_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string description = 7;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string description = 7;</code>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string description = 7;</code>
       */
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000040);
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>optional string description = 7;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        description_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object card_ = "";
      /**
       * <code>optional string card = 8;</code>
       */
      public boolean hasCard() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string card = 8;</code>
       */
      public java.lang.String getCard() {
        java.lang.Object ref = card_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            card_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string card = 8;</code>
       */
      public com.google.protobuf.ByteString
          getCardBytes() {
        java.lang.Object ref = card_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          card_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string card = 8;</code>
       */
      public Builder setCard(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        card_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string card = 8;</code>
       */
      public Builder clearCard() {
        bitField0_ = (bitField0_ & ~0x00000080);
        card_ = getDefaultInstance().getCard();
        onChanged();
        return this;
      }
      /**
       * <code>optional string card = 8;</code>
       */
      public Builder setCardBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        card_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.ilmservice.personalbudget.Transaction)
    }

    static {
      defaultInstance = new Transaction(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.ilmservice.personalbudget.Transaction)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ilmservice_personalbudget_Transaction_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_ilmservice_personalbudget_Transaction_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nData.proto\022\035com.ilmservice.personalbud" +
      "get\"\215\001\n\013Transaction\022\n\n\002id\030\001 \001(\014\022\022\n\ncateg" +
      "oryId\030\002 \001(\r\022\016\n\006tagIds\030\003 \003(\r\022\016\n\006userId\030\004 " +
      "\001(\r\022\014\n\004date\030\005 \001(\004\022\r\n\005cents\030\006 \001(\021\022\023\n\013desc" +
      "ription\030\007 \001(\t\022\014\n\004card\030\010 \001(\tB)\n\'com.ilmse" +
      "rvice.personalbudget.protobufs"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_ilmservice_personalbudget_Transaction_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ilmservice_personalbudget_Transaction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_ilmservice_personalbudget_Transaction_descriptor,
        new java.lang.String[] { "Id", "CategoryId", "TagIds", "UserId", "Date", "Cents", "Description", "Card", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
