// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Events.proto

package com.ilmservice.personalbudget.protobufs;

public final class Events {
  private Events() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface EventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ilmservice.personalbudget.Event)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional uint32 id = 1;</code>
     */
    int getId();

    /**
     * <code>optional uint32 userId = 2;</code>
     */
    boolean hasUserId();
    /**
     * <code>optional uint32 userId = 2;</code>
     */
    int getUserId();

    /**
     * <code>optional int64 timestamp = 3;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>optional int64 timestamp = 3;</code>
     */
    long getTimestamp();

    /**
     * <code>optional .com.ilmservice.personalbudget.UploadSpreadsheetEvent uploadSpreadsheetEvent = 10;</code>
     */
    boolean hasUploadSpreadsheetEvent();
    /**
     * <code>optional .com.ilmservice.personalbudget.UploadSpreadsheetEvent uploadSpreadsheetEvent = 10;</code>
     */
    com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent getUploadSpreadsheetEvent();
    /**
     * <code>optional .com.ilmservice.personalbudget.UploadSpreadsheetEvent uploadSpreadsheetEvent = 10;</code>
     */
    com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEventOrBuilder getUploadSpreadsheetEventOrBuilder();
  }
  /**
   * Protobuf type {@code com.ilmservice.personalbudget.Event}
   */
  public static final class Event extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.ilmservice.personalbudget.Event)
      EventOrBuilder {
    // Use Event.newBuilder() to construct.
    private Event(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Event(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Event defaultInstance;
    public static Event getDefaultInstance() {
      return defaultInstance;
    }

    public Event getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Event(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              userId_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              timestamp_ = input.readInt64();
              break;
            }
            case 82: {
              com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent.Builder subBuilder = null;
              if (eventTypeCase_ == 10) {
                subBuilder = ((com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent) eventType_).toBuilder();
              }
              eventType_ = input.readMessage(com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent) eventType_);
                eventType_ = subBuilder.buildPartial();
              }
              eventTypeCase_ = 10;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ilmservice.personalbudget.protobufs.Events.internal_static_com_ilmservice_personalbudget_Event_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ilmservice.personalbudget.protobufs.Events.internal_static_com_ilmservice_personalbudget_Event_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ilmservice.personalbudget.protobufs.Events.Event.class, com.ilmservice.personalbudget.protobufs.Events.Event.Builder.class);
    }

    public static com.google.protobuf.Parser<Event> PARSER =
        new com.google.protobuf.AbstractParser<Event>() {
      public Event parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Event(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Event> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    private int eventTypeCase_ = 0;
    private java.lang.Object eventType_;
    public enum EventTypeCase
        implements com.google.protobuf.Internal.EnumLite {
      UPLOADSPREADSHEETEVENT(10),
      EVENTTYPE_NOT_SET(0);
      private int value = 0;
      private EventTypeCase(int value) {
        this.value = value;
      }
      public static EventTypeCase valueOf(int value) {
        switch (value) {
          case 10: return UPLOADSPREADSHEETEVENT;
          case 0: return EVENTTYPE_NOT_SET;
          default: throw new java.lang.IllegalArgumentException(
            "Value is undefined for this oneof enum.");
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public EventTypeCase
    getEventTypeCase() {
      return EventTypeCase.valueOf(
          eventTypeCase_);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional uint32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int USERID_FIELD_NUMBER = 2;
    private int userId_;
    /**
     * <code>optional uint32 userId = 2;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint32 userId = 2;</code>
     */
    public int getUserId() {
      return userId_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private long timestamp_;
    /**
     * <code>optional int64 timestamp = 3;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 timestamp = 3;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int UPLOADSPREADSHEETEVENT_FIELD_NUMBER = 10;
    /**
     * <code>optional .com.ilmservice.personalbudget.UploadSpreadsheetEvent uploadSpreadsheetEvent = 10;</code>
     */
    public boolean hasUploadSpreadsheetEvent() {
      return eventTypeCase_ == 10;
    }
    /**
     * <code>optional .com.ilmservice.personalbudget.UploadSpreadsheetEvent uploadSpreadsheetEvent = 10;</code>
     */
    public com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent getUploadSpreadsheetEvent() {
      if (eventTypeCase_ == 10) {
         return (com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent) eventType_;
      }
      return com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent.getDefaultInstance();
    }
    /**
     * <code>optional .com.ilmservice.personalbudget.UploadSpreadsheetEvent uploadSpreadsheetEvent = 10;</code>
     */
    public com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEventOrBuilder getUploadSpreadsheetEventOrBuilder() {
      if (eventTypeCase_ == 10) {
         return (com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent) eventType_;
      }
      return com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent.getDefaultInstance();
    }

    private void initFields() {
      id_ = 0;
      userId_ = 0;
      timestamp_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, userId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, timestamp_);
      }
      if (eventTypeCase_ == 10) {
        output.writeMessage(10, (com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent) eventType_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, userId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, timestamp_);
      }
      if (eventTypeCase_ == 10) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, (com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent) eventType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.ilmservice.personalbudget.protobufs.Events.Event parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ilmservice.personalbudget.protobufs.Events.Event parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ilmservice.personalbudget.protobufs.Events.Event parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ilmservice.personalbudget.protobufs.Events.Event parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ilmservice.personalbudget.protobufs.Events.Event parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ilmservice.personalbudget.protobufs.Events.Event parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.ilmservice.personalbudget.protobufs.Events.Event parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.ilmservice.personalbudget.protobufs.Events.Event parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.ilmservice.personalbudget.protobufs.Events.Event parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ilmservice.personalbudget.protobufs.Events.Event parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ilmservice.personalbudget.protobufs.Events.Event prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ilmservice.personalbudget.Event}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ilmservice.personalbudget.Event)
        com.ilmservice.personalbudget.protobufs.Events.EventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ilmservice.personalbudget.protobufs.Events.internal_static_com_ilmservice_personalbudget_Event_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ilmservice.personalbudget.protobufs.Events.internal_static_com_ilmservice_personalbudget_Event_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ilmservice.personalbudget.protobufs.Events.Event.class, com.ilmservice.personalbudget.protobufs.Events.Event.Builder.class);
      }

      // Construct using com.ilmservice.personalbudget.protobufs.Events.Event.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        eventTypeCase_ = 0;
        eventType_ = null;
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ilmservice.personalbudget.protobufs.Events.internal_static_com_ilmservice_personalbudget_Event_descriptor;
      }

      public com.ilmservice.personalbudget.protobufs.Events.Event getDefaultInstanceForType() {
        return com.ilmservice.personalbudget.protobufs.Events.Event.getDefaultInstance();
      }

      public com.ilmservice.personalbudget.protobufs.Events.Event build() {
        com.ilmservice.personalbudget.protobufs.Events.Event result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ilmservice.personalbudget.protobufs.Events.Event buildPartial() {
        com.ilmservice.personalbudget.protobufs.Events.Event result = new com.ilmservice.personalbudget.protobufs.Events.Event(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.timestamp_ = timestamp_;
        if (eventTypeCase_ == 10) {
          if (uploadSpreadsheetEventBuilder_ == null) {
            result.eventType_ = eventType_;
          } else {
            result.eventType_ = uploadSpreadsheetEventBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.eventTypeCase_ = eventTypeCase_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ilmservice.personalbudget.protobufs.Events.Event) {
          return mergeFrom((com.ilmservice.personalbudget.protobufs.Events.Event)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ilmservice.personalbudget.protobufs.Events.Event other) {
        if (other == com.ilmservice.personalbudget.protobufs.Events.Event.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        switch (other.getEventTypeCase()) {
          case UPLOADSPREADSHEETEVENT: {
            mergeUploadSpreadsheetEvent(other.getUploadSpreadsheetEvent());
            break;
          }
          case EVENTTYPE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ilmservice.personalbudget.protobufs.Events.Event parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ilmservice.personalbudget.protobufs.Events.Event) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int eventTypeCase_ = 0;
      private java.lang.Object eventType_;
      public EventTypeCase
          getEventTypeCase() {
        return EventTypeCase.valueOf(
            eventTypeCase_);
      }

      public Builder clearEventType() {
        eventTypeCase_ = 0;
        eventType_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private int id_ ;
      /**
       * <code>optional uint32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional uint32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private int userId_ ;
      /**
       * <code>optional uint32 userId = 2;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint32 userId = 2;</code>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>optional uint32 userId = 2;</code>
       */
      public Builder setUserId(int value) {
        bitField0_ |= 0x00000002;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 userId = 2;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userId_ = 0;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>optional int64 timestamp = 3;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 timestamp = 3;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional int64 timestamp = 3;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000004;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 timestamp = 3;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilder<
          com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent, com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent.Builder, com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEventOrBuilder> uploadSpreadsheetEventBuilder_;
      /**
       * <code>optional .com.ilmservice.personalbudget.UploadSpreadsheetEvent uploadSpreadsheetEvent = 10;</code>
       */
      public boolean hasUploadSpreadsheetEvent() {
        return eventTypeCase_ == 10;
      }
      /**
       * <code>optional .com.ilmservice.personalbudget.UploadSpreadsheetEvent uploadSpreadsheetEvent = 10;</code>
       */
      public com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent getUploadSpreadsheetEvent() {
        if (uploadSpreadsheetEventBuilder_ == null) {
          if (eventTypeCase_ == 10) {
            return (com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent) eventType_;
          }
          return com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent.getDefaultInstance();
        } else {
          if (eventTypeCase_ == 10) {
            return uploadSpreadsheetEventBuilder_.getMessage();
          }
          return com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.ilmservice.personalbudget.UploadSpreadsheetEvent uploadSpreadsheetEvent = 10;</code>
       */
      public Builder setUploadSpreadsheetEvent(com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent value) {
        if (uploadSpreadsheetEventBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          eventType_ = value;
          onChanged();
        } else {
          uploadSpreadsheetEventBuilder_.setMessage(value);
        }
        eventTypeCase_ = 10;
        return this;
      }
      /**
       * <code>optional .com.ilmservice.personalbudget.UploadSpreadsheetEvent uploadSpreadsheetEvent = 10;</code>
       */
      public Builder setUploadSpreadsheetEvent(
          com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent.Builder builderForValue) {
        if (uploadSpreadsheetEventBuilder_ == null) {
          eventType_ = builderForValue.build();
          onChanged();
        } else {
          uploadSpreadsheetEventBuilder_.setMessage(builderForValue.build());
        }
        eventTypeCase_ = 10;
        return this;
      }
      /**
       * <code>optional .com.ilmservice.personalbudget.UploadSpreadsheetEvent uploadSpreadsheetEvent = 10;</code>
       */
      public Builder mergeUploadSpreadsheetEvent(com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent value) {
        if (uploadSpreadsheetEventBuilder_ == null) {
          if (eventTypeCase_ == 10 &&
              eventType_ != com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent.getDefaultInstance()) {
            eventType_ = com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent.newBuilder((com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent) eventType_)
                .mergeFrom(value).buildPartial();
          } else {
            eventType_ = value;
          }
          onChanged();
        } else {
          if (eventTypeCase_ == 10) {
            uploadSpreadsheetEventBuilder_.mergeFrom(value);
          }
          uploadSpreadsheetEventBuilder_.setMessage(value);
        }
        eventTypeCase_ = 10;
        return this;
      }
      /**
       * <code>optional .com.ilmservice.personalbudget.UploadSpreadsheetEvent uploadSpreadsheetEvent = 10;</code>
       */
      public Builder clearUploadSpreadsheetEvent() {
        if (uploadSpreadsheetEventBuilder_ == null) {
          if (eventTypeCase_ == 10) {
            eventTypeCase_ = 0;
            eventType_ = null;
            onChanged();
          }
        } else {
          if (eventTypeCase_ == 10) {
            eventTypeCase_ = 0;
            eventType_ = null;
          }
          uploadSpreadsheetEventBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .com.ilmservice.personalbudget.UploadSpreadsheetEvent uploadSpreadsheetEvent = 10;</code>
       */
      public com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent.Builder getUploadSpreadsheetEventBuilder() {
        return getUploadSpreadsheetEventFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.ilmservice.personalbudget.UploadSpreadsheetEvent uploadSpreadsheetEvent = 10;</code>
       */
      public com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEventOrBuilder getUploadSpreadsheetEventOrBuilder() {
        if ((eventTypeCase_ == 10) && (uploadSpreadsheetEventBuilder_ != null)) {
          return uploadSpreadsheetEventBuilder_.getMessageOrBuilder();
        } else {
          if (eventTypeCase_ == 10) {
            return (com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent) eventType_;
          }
          return com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.ilmservice.personalbudget.UploadSpreadsheetEvent uploadSpreadsheetEvent = 10;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent, com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent.Builder, com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEventOrBuilder> 
          getUploadSpreadsheetEventFieldBuilder() {
        if (uploadSpreadsheetEventBuilder_ == null) {
          if (!(eventTypeCase_ == 10)) {
            eventType_ = com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent.getDefaultInstance();
          }
          uploadSpreadsheetEventBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent, com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent.Builder, com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEventOrBuilder>(
                  (com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent) eventType_,
                  getParentForChildren(),
                  isClean());
          eventType_ = null;
        }
        eventTypeCase_ = 10;
        return uploadSpreadsheetEventBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.ilmservice.personalbudget.Event)
    }

    static {
      defaultInstance = new Event(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.ilmservice.personalbudget.Event)
  }

  public interface UploadSpreadsheetEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ilmservice.personalbudget.UploadSpreadsheetEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string filename = 3;</code>
     */
    boolean hasFilename();
    /**
     * <code>optional string filename = 3;</code>
     */
    java.lang.String getFilename();
    /**
     * <code>optional string filename = 3;</code>
     */
    com.google.protobuf.ByteString
        getFilenameBytes();

    /**
     * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
     */
    java.util.List<com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow> 
        getRowsList();
    /**
     * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
     */
    com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow getRows(int index);
    /**
     * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
     */
    int getRowsCount();
    /**
     * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
     */
    java.util.List<? extends com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRowOrBuilder> 
        getRowsOrBuilderList();
    /**
     * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
     */
    com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRowOrBuilder getRowsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.ilmservice.personalbudget.UploadSpreadsheetEvent}
   */
  public static final class UploadSpreadsheetEvent extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.ilmservice.personalbudget.UploadSpreadsheetEvent)
      UploadSpreadsheetEventOrBuilder {
    // Use UploadSpreadsheetEvent.newBuilder() to construct.
    private UploadSpreadsheetEvent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private UploadSpreadsheetEvent(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final UploadSpreadsheetEvent defaultInstance;
    public static UploadSpreadsheetEvent getDefaultInstance() {
      return defaultInstance;
    }

    public UploadSpreadsheetEvent getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private UploadSpreadsheetEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              filename_ = bs;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                rows_ = new java.util.ArrayList<com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow>();
                mutable_bitField0_ |= 0x00000002;
              }
              rows_.add(input.readMessage(com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          rows_ = java.util.Collections.unmodifiableList(rows_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ilmservice.personalbudget.protobufs.Events.internal_static_com_ilmservice_personalbudget_UploadSpreadsheetEvent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ilmservice.personalbudget.protobufs.Events.internal_static_com_ilmservice_personalbudget_UploadSpreadsheetEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent.class, com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent.Builder.class);
    }

    public static com.google.protobuf.Parser<UploadSpreadsheetEvent> PARSER =
        new com.google.protobuf.AbstractParser<UploadSpreadsheetEvent>() {
      public UploadSpreadsheetEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UploadSpreadsheetEvent(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<UploadSpreadsheetEvent> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int FILENAME_FIELD_NUMBER = 3;
    private java.lang.Object filename_;
    /**
     * <code>optional string filename = 3;</code>
     */
    public boolean hasFilename() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string filename = 3;</code>
     */
    public java.lang.String getFilename() {
      java.lang.Object ref = filename_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          filename_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string filename = 3;</code>
     */
    public com.google.protobuf.ByteString
        getFilenameBytes() {
      java.lang.Object ref = filename_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filename_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ROWS_FIELD_NUMBER = 4;
    private java.util.List<com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow> rows_;
    /**
     * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
     */
    public java.util.List<com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow> getRowsList() {
      return rows_;
    }
    /**
     * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
     */
    public java.util.List<? extends com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRowOrBuilder> 
        getRowsOrBuilderList() {
      return rows_;
    }
    /**
     * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
     */
    public int getRowsCount() {
      return rows_.size();
    }
    /**
     * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
     */
    public com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow getRows(int index) {
      return rows_.get(index);
    }
    /**
     * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
     */
    public com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRowOrBuilder getRowsOrBuilder(
        int index) {
      return rows_.get(index);
    }

    private void initFields() {
      filename_ = "";
      rows_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(3, getFilenameBytes());
      }
      for (int i = 0; i < rows_.size(); i++) {
        output.writeMessage(4, rows_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getFilenameBytes());
      }
      for (int i = 0; i < rows_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, rows_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ilmservice.personalbudget.UploadSpreadsheetEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ilmservice.personalbudget.UploadSpreadsheetEvent)
        com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ilmservice.personalbudget.protobufs.Events.internal_static_com_ilmservice_personalbudget_UploadSpreadsheetEvent_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ilmservice.personalbudget.protobufs.Events.internal_static_com_ilmservice_personalbudget_UploadSpreadsheetEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent.class, com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent.Builder.class);
      }

      // Construct using com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRowsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        filename_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (rowsBuilder_ == null) {
          rows_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          rowsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ilmservice.personalbudget.protobufs.Events.internal_static_com_ilmservice_personalbudget_UploadSpreadsheetEvent_descriptor;
      }

      public com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent getDefaultInstanceForType() {
        return com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent.getDefaultInstance();
      }

      public com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent build() {
        com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent buildPartial() {
        com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent result = new com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.filename_ = filename_;
        if (rowsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            rows_ = java.util.Collections.unmodifiableList(rows_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.rows_ = rows_;
        } else {
          result.rows_ = rowsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent) {
          return mergeFrom((com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent other) {
        if (other == com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent.getDefaultInstance()) return this;
        if (other.hasFilename()) {
          bitField0_ |= 0x00000001;
          filename_ = other.filename_;
          onChanged();
        }
        if (rowsBuilder_ == null) {
          if (!other.rows_.isEmpty()) {
            if (rows_.isEmpty()) {
              rows_ = other.rows_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureRowsIsMutable();
              rows_.addAll(other.rows_);
            }
            onChanged();
          }
        } else {
          if (!other.rows_.isEmpty()) {
            if (rowsBuilder_.isEmpty()) {
              rowsBuilder_.dispose();
              rowsBuilder_ = null;
              rows_ = other.rows_;
              bitField0_ = (bitField0_ & ~0x00000002);
              rowsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRowsFieldBuilder() : null;
            } else {
              rowsBuilder_.addAllMessages(other.rows_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object filename_ = "";
      /**
       * <code>optional string filename = 3;</code>
       */
      public boolean hasFilename() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string filename = 3;</code>
       */
      public java.lang.String getFilename() {
        java.lang.Object ref = filename_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            filename_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string filename = 3;</code>
       */
      public com.google.protobuf.ByteString
          getFilenameBytes() {
        java.lang.Object ref = filename_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          filename_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string filename = 3;</code>
       */
      public Builder setFilename(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        filename_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string filename = 3;</code>
       */
      public Builder clearFilename() {
        bitField0_ = (bitField0_ & ~0x00000001);
        filename_ = getDefaultInstance().getFilename();
        onChanged();
        return this;
      }
      /**
       * <code>optional string filename = 3;</code>
       */
      public Builder setFilenameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        filename_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow> rows_ =
        java.util.Collections.emptyList();
      private void ensureRowsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          rows_ = new java.util.ArrayList<com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow>(rows_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow, com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow.Builder, com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRowOrBuilder> rowsBuilder_;

      /**
       * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
       */
      public java.util.List<com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow> getRowsList() {
        if (rowsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(rows_);
        } else {
          return rowsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
       */
      public int getRowsCount() {
        if (rowsBuilder_ == null) {
          return rows_.size();
        } else {
          return rowsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
       */
      public com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow getRows(int index) {
        if (rowsBuilder_ == null) {
          return rows_.get(index);
        } else {
          return rowsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
       */
      public Builder setRows(
          int index, com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow value) {
        if (rowsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRowsIsMutable();
          rows_.set(index, value);
          onChanged();
        } else {
          rowsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
       */
      public Builder setRows(
          int index, com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow.Builder builderForValue) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          rows_.set(index, builderForValue.build());
          onChanged();
        } else {
          rowsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
       */
      public Builder addRows(com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow value) {
        if (rowsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRowsIsMutable();
          rows_.add(value);
          onChanged();
        } else {
          rowsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
       */
      public Builder addRows(
          int index, com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow value) {
        if (rowsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRowsIsMutable();
          rows_.add(index, value);
          onChanged();
        } else {
          rowsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
       */
      public Builder addRows(
          com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow.Builder builderForValue) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          rows_.add(builderForValue.build());
          onChanged();
        } else {
          rowsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
       */
      public Builder addRows(
          int index, com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow.Builder builderForValue) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          rows_.add(index, builderForValue.build());
          onChanged();
        } else {
          rowsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
       */
      public Builder addAllRows(
          java.lang.Iterable<? extends com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow> values) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, rows_);
          onChanged();
        } else {
          rowsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
       */
      public Builder clearRows() {
        if (rowsBuilder_ == null) {
          rows_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          rowsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
       */
      public Builder removeRows(int index) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          rows_.remove(index);
          onChanged();
        } else {
          rowsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
       */
      public com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow.Builder getRowsBuilder(
          int index) {
        return getRowsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
       */
      public com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRowOrBuilder getRowsOrBuilder(
          int index) {
        if (rowsBuilder_ == null) {
          return rows_.get(index);  } else {
          return rowsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
       */
      public java.util.List<? extends com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRowOrBuilder> 
           getRowsOrBuilderList() {
        if (rowsBuilder_ != null) {
          return rowsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(rows_);
        }
      }
      /**
       * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
       */
      public com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow.Builder addRowsBuilder() {
        return getRowsFieldBuilder().addBuilder(
            com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow.getDefaultInstance());
      }
      /**
       * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
       */
      public com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow.Builder addRowsBuilder(
          int index) {
        return getRowsFieldBuilder().addBuilder(
            index, com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow.getDefaultInstance());
      }
      /**
       * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
       */
      public java.util.List<com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow.Builder> 
           getRowsBuilderList() {
        return getRowsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow, com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow.Builder, com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRowOrBuilder> 
          getRowsFieldBuilder() {
        if (rowsBuilder_ == null) {
          rowsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow, com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow.Builder, com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRowOrBuilder>(
                  rows_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          rows_ = null;
        }
        return rowsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.ilmservice.personalbudget.UploadSpreadsheetEvent)
    }

    static {
      defaultInstance = new UploadSpreadsheetEvent(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.ilmservice.personalbudget.UploadSpreadsheetEvent)
  }

  public interface SpreadsheetRowOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ilmservice.personalbudget.SpreadsheetRow)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string fields = 1;</code>
     */
    com.google.protobuf.ProtocolStringList
        getFieldsList();
    /**
     * <code>repeated string fields = 1;</code>
     */
    int getFieldsCount();
    /**
     * <code>repeated string fields = 1;</code>
     */
    java.lang.String getFields(int index);
    /**
     * <code>repeated string fields = 1;</code>
     */
    com.google.protobuf.ByteString
        getFieldsBytes(int index);
  }
  /**
   * Protobuf type {@code com.ilmservice.personalbudget.SpreadsheetRow}
   */
  public static final class SpreadsheetRow extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.ilmservice.personalbudget.SpreadsheetRow)
      SpreadsheetRowOrBuilder {
    // Use SpreadsheetRow.newBuilder() to construct.
    private SpreadsheetRow(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SpreadsheetRow(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SpreadsheetRow defaultInstance;
    public static SpreadsheetRow getDefaultInstance() {
      return defaultInstance;
    }

    public SpreadsheetRow getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SpreadsheetRow(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                fields_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              fields_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          fields_ = fields_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ilmservice.personalbudget.protobufs.Events.internal_static_com_ilmservice_personalbudget_SpreadsheetRow_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ilmservice.personalbudget.protobufs.Events.internal_static_com_ilmservice_personalbudget_SpreadsheetRow_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow.class, com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow.Builder.class);
    }

    public static com.google.protobuf.Parser<SpreadsheetRow> PARSER =
        new com.google.protobuf.AbstractParser<SpreadsheetRow>() {
      public SpreadsheetRow parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SpreadsheetRow(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SpreadsheetRow> getParserForType() {
      return PARSER;
    }

    public static final int FIELDS_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList fields_;
    /**
     * <code>repeated string fields = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getFieldsList() {
      return fields_;
    }
    /**
     * <code>repeated string fields = 1;</code>
     */
    public int getFieldsCount() {
      return fields_.size();
    }
    /**
     * <code>repeated string fields = 1;</code>
     */
    public java.lang.String getFields(int index) {
      return fields_.get(index);
    }
    /**
     * <code>repeated string fields = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFieldsBytes(int index) {
      return fields_.getByteString(index);
    }

    private void initFields() {
      fields_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < fields_.size(); i++) {
        output.writeBytes(1, fields_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < fields_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(fields_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getFieldsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ilmservice.personalbudget.SpreadsheetRow}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ilmservice.personalbudget.SpreadsheetRow)
        com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRowOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ilmservice.personalbudget.protobufs.Events.internal_static_com_ilmservice_personalbudget_SpreadsheetRow_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ilmservice.personalbudget.protobufs.Events.internal_static_com_ilmservice_personalbudget_SpreadsheetRow_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow.class, com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow.Builder.class);
      }

      // Construct using com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        fields_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ilmservice.personalbudget.protobufs.Events.internal_static_com_ilmservice_personalbudget_SpreadsheetRow_descriptor;
      }

      public com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow getDefaultInstanceForType() {
        return com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow.getDefaultInstance();
      }

      public com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow build() {
        com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow buildPartial() {
        com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow result = new com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          fields_ = fields_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.fields_ = fields_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow) {
          return mergeFrom((com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow other) {
        if (other == com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow.getDefaultInstance()) return this;
        if (!other.fields_.isEmpty()) {
          if (fields_.isEmpty()) {
            fields_ = other.fields_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureFieldsIsMutable();
            fields_.addAll(other.fields_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList fields_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureFieldsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          fields_ = new com.google.protobuf.LazyStringArrayList(fields_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string fields = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getFieldsList() {
        return fields_.getUnmodifiableView();
      }
      /**
       * <code>repeated string fields = 1;</code>
       */
      public int getFieldsCount() {
        return fields_.size();
      }
      /**
       * <code>repeated string fields = 1;</code>
       */
      public java.lang.String getFields(int index) {
        return fields_.get(index);
      }
      /**
       * <code>repeated string fields = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFieldsBytes(int index) {
        return fields_.getByteString(index);
      }
      /**
       * <code>repeated string fields = 1;</code>
       */
      public Builder setFields(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFieldsIsMutable();
        fields_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string fields = 1;</code>
       */
      public Builder addFields(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFieldsIsMutable();
        fields_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string fields = 1;</code>
       */
      public Builder addAllFields(
          java.lang.Iterable<java.lang.String> values) {
        ensureFieldsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, fields_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string fields = 1;</code>
       */
      public Builder clearFields() {
        fields_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string fields = 1;</code>
       */
      public Builder addFieldsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFieldsIsMutable();
        fields_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.ilmservice.personalbudget.SpreadsheetRow)
    }

    static {
      defaultInstance = new SpreadsheetRow(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.ilmservice.personalbudget.SpreadsheetRow)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ilmservice_personalbudget_Event_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_ilmservice_personalbudget_Event_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ilmservice_personalbudget_UploadSpreadsheetEvent_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_ilmservice_personalbudget_UploadSpreadsheetEvent_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ilmservice_personalbudget_SpreadsheetRow_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_ilmservice_personalbudget_SpreadsheetRow_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Events.proto\022\035com.ilmservice.personalb" +
      "udget\"\235\001\n\005Event\022\n\n\002id\030\001 \001(\r\022\016\n\006userId\030\002 " +
      "\001(\r\022\021\n\ttimestamp\030\003 \001(\003\022W\n\026uploadSpreadsh" +
      "eetEvent\030\n \001(\01325.com.ilmservice.personal" +
      "budget.UploadSpreadsheetEventH\000B\014\n\nevent" +
      "_type\"g\n\026UploadSpreadsheetEvent\022\020\n\010filen" +
      "ame\030\003 \001(\t\022;\n\004rows\030\004 \003(\0132-.com.ilmservice" +
      ".personalbudget.SpreadsheetRow\" \n\016Spread" +
      "sheetRow\022\016\n\006fields\030\001 \003(\tB)\n\'com.ilmservi" +
      "ce.personalbudget.protobufs"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_ilmservice_personalbudget_Event_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ilmservice_personalbudget_Event_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_ilmservice_personalbudget_Event_descriptor,
        new java.lang.String[] { "Id", "UserId", "Timestamp", "UploadSpreadsheetEvent", "EventType", });
    internal_static_com_ilmservice_personalbudget_UploadSpreadsheetEvent_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ilmservice_personalbudget_UploadSpreadsheetEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_ilmservice_personalbudget_UploadSpreadsheetEvent_descriptor,
        new java.lang.String[] { "Filename", "Rows", });
    internal_static_com_ilmservice_personalbudget_SpreadsheetRow_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_ilmservice_personalbudget_SpreadsheetRow_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_ilmservice_personalbudget_SpreadsheetRow_descriptor,
        new java.lang.String[] { "Fields", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
