// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Events.proto

package com.ilmservice.personalbudget.protobufs;

public final class Events {
  private Events() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UploadSpreadsheetEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ilmservice.personalbudget.UploadSpreadsheetEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint32 userId = 1;</code>
     */
    boolean hasUserId();
    /**
     * <code>optional uint32 userId = 1;</code>
     */
    int getUserId();

    /**
     * <code>optional int64 timestamp = 2;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>optional int64 timestamp = 2;</code>
     */
    long getTimestamp();

    /**
     * <code>optional string filename = 3;</code>
     */
    boolean hasFilename();
    /**
     * <code>optional string filename = 3;</code>
     */
    java.lang.String getFilename();
    /**
     * <code>optional string filename = 3;</code>
     */
    com.google.protobuf.ByteString
        getFilenameBytes();

    /**
     * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
     */
    java.util.List<com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow> 
        getRowsList();
    /**
     * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
     */
    com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow getRows(int index);
    /**
     * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
     */
    int getRowsCount();
    /**
     * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
     */
    java.util.List<? extends com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRowOrBuilder> 
        getRowsOrBuilderList();
    /**
     * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
     */
    com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRowOrBuilder getRowsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.ilmservice.personalbudget.UploadSpreadsheetEvent}
   */
  public static final class UploadSpreadsheetEvent extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.ilmservice.personalbudget.UploadSpreadsheetEvent)
      UploadSpreadsheetEventOrBuilder {
    // Use UploadSpreadsheetEvent.newBuilder() to construct.
    private UploadSpreadsheetEvent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private UploadSpreadsheetEvent(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final UploadSpreadsheetEvent defaultInstance;
    public static UploadSpreadsheetEvent getDefaultInstance() {
      return defaultInstance;
    }

    public UploadSpreadsheetEvent getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private UploadSpreadsheetEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              userId_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              timestamp_ = input.readInt64();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              filename_ = bs;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                rows_ = new java.util.ArrayList<com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow>();
                mutable_bitField0_ |= 0x00000008;
              }
              rows_.add(input.readMessage(com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          rows_ = java.util.Collections.unmodifiableList(rows_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ilmservice.personalbudget.protobufs.Events.internal_static_com_ilmservice_personalbudget_UploadSpreadsheetEvent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ilmservice.personalbudget.protobufs.Events.internal_static_com_ilmservice_personalbudget_UploadSpreadsheetEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent.class, com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent.Builder.class);
    }

    public static com.google.protobuf.Parser<UploadSpreadsheetEvent> PARSER =
        new com.google.protobuf.AbstractParser<UploadSpreadsheetEvent>() {
      public UploadSpreadsheetEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UploadSpreadsheetEvent(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<UploadSpreadsheetEvent> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int USERID_FIELD_NUMBER = 1;
    private int userId_;
    /**
     * <code>optional uint32 userId = 1;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 userId = 1;</code>
     */
    public int getUserId() {
      return userId_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_;
    /**
     * <code>optional int64 timestamp = 2;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 timestamp = 2;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int FILENAME_FIELD_NUMBER = 3;
    private java.lang.Object filename_;
    /**
     * <code>optional string filename = 3;</code>
     */
    public boolean hasFilename() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string filename = 3;</code>
     */
    public java.lang.String getFilename() {
      java.lang.Object ref = filename_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          filename_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string filename = 3;</code>
     */
    public com.google.protobuf.ByteString
        getFilenameBytes() {
      java.lang.Object ref = filename_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filename_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ROWS_FIELD_NUMBER = 4;
    private java.util.List<com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow> rows_;
    /**
     * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
     */
    public java.util.List<com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow> getRowsList() {
      return rows_;
    }
    /**
     * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
     */
    public java.util.List<? extends com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRowOrBuilder> 
        getRowsOrBuilderList() {
      return rows_;
    }
    /**
     * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
     */
    public int getRowsCount() {
      return rows_.size();
    }
    /**
     * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
     */
    public com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow getRows(int index) {
      return rows_.get(index);
    }
    /**
     * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
     */
    public com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRowOrBuilder getRowsOrBuilder(
        int index) {
      return rows_.get(index);
    }

    private void initFields() {
      userId_ = 0;
      timestamp_ = 0L;
      filename_ = "";
      rows_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, timestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getFilenameBytes());
      }
      for (int i = 0; i < rows_.size(); i++) {
        output.writeMessage(4, rows_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, userId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, timestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getFilenameBytes());
      }
      for (int i = 0; i < rows_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, rows_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ilmservice.personalbudget.UploadSpreadsheetEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ilmservice.personalbudget.UploadSpreadsheetEvent)
        com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ilmservice.personalbudget.protobufs.Events.internal_static_com_ilmservice_personalbudget_UploadSpreadsheetEvent_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ilmservice.personalbudget.protobufs.Events.internal_static_com_ilmservice_personalbudget_UploadSpreadsheetEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent.class, com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent.Builder.class);
      }

      // Construct using com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRowsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        filename_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        if (rowsBuilder_ == null) {
          rows_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          rowsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ilmservice.personalbudget.protobufs.Events.internal_static_com_ilmservice_personalbudget_UploadSpreadsheetEvent_descriptor;
      }

      public com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent getDefaultInstanceForType() {
        return com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent.getDefaultInstance();
      }

      public com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent build() {
        com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent buildPartial() {
        com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent result = new com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.filename_ = filename_;
        if (rowsBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            rows_ = java.util.Collections.unmodifiableList(rows_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.rows_ = rows_;
        } else {
          result.rows_ = rowsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent) {
          return mergeFrom((com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent other) {
        if (other == com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasFilename()) {
          bitField0_ |= 0x00000004;
          filename_ = other.filename_;
          onChanged();
        }
        if (rowsBuilder_ == null) {
          if (!other.rows_.isEmpty()) {
            if (rows_.isEmpty()) {
              rows_ = other.rows_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureRowsIsMutable();
              rows_.addAll(other.rows_);
            }
            onChanged();
          }
        } else {
          if (!other.rows_.isEmpty()) {
            if (rowsBuilder_.isEmpty()) {
              rowsBuilder_.dispose();
              rowsBuilder_ = null;
              rows_ = other.rows_;
              bitField0_ = (bitField0_ & ~0x00000008);
              rowsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRowsFieldBuilder() : null;
            } else {
              rowsBuilder_.addAllMessages(other.rows_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ilmservice.personalbudget.protobufs.Events.UploadSpreadsheetEvent) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int userId_ ;
      /**
       * <code>optional uint32 userId = 1;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 userId = 1;</code>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>optional uint32 userId = 1;</code>
       */
      public Builder setUserId(int value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 userId = 1;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>optional int64 timestamp = 2;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 timestamp = 2;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional int64 timestamp = 2;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000002;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 timestamp = 2;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object filename_ = "";
      /**
       * <code>optional string filename = 3;</code>
       */
      public boolean hasFilename() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string filename = 3;</code>
       */
      public java.lang.String getFilename() {
        java.lang.Object ref = filename_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            filename_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string filename = 3;</code>
       */
      public com.google.protobuf.ByteString
          getFilenameBytes() {
        java.lang.Object ref = filename_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          filename_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string filename = 3;</code>
       */
      public Builder setFilename(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        filename_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string filename = 3;</code>
       */
      public Builder clearFilename() {
        bitField0_ = (bitField0_ & ~0x00000004);
        filename_ = getDefaultInstance().getFilename();
        onChanged();
        return this;
      }
      /**
       * <code>optional string filename = 3;</code>
       */
      public Builder setFilenameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        filename_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow> rows_ =
        java.util.Collections.emptyList();
      private void ensureRowsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          rows_ = new java.util.ArrayList<com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow>(rows_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow, com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow.Builder, com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRowOrBuilder> rowsBuilder_;

      /**
       * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
       */
      public java.util.List<com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow> getRowsList() {
        if (rowsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(rows_);
        } else {
          return rowsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
       */
      public int getRowsCount() {
        if (rowsBuilder_ == null) {
          return rows_.size();
        } else {
          return rowsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
       */
      public com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow getRows(int index) {
        if (rowsBuilder_ == null) {
          return rows_.get(index);
        } else {
          return rowsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
       */
      public Builder setRows(
          int index, com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow value) {
        if (rowsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRowsIsMutable();
          rows_.set(index, value);
          onChanged();
        } else {
          rowsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
       */
      public Builder setRows(
          int index, com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow.Builder builderForValue) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          rows_.set(index, builderForValue.build());
          onChanged();
        } else {
          rowsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
       */
      public Builder addRows(com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow value) {
        if (rowsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRowsIsMutable();
          rows_.add(value);
          onChanged();
        } else {
          rowsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
       */
      public Builder addRows(
          int index, com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow value) {
        if (rowsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRowsIsMutable();
          rows_.add(index, value);
          onChanged();
        } else {
          rowsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
       */
      public Builder addRows(
          com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow.Builder builderForValue) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          rows_.add(builderForValue.build());
          onChanged();
        } else {
          rowsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
       */
      public Builder addRows(
          int index, com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow.Builder builderForValue) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          rows_.add(index, builderForValue.build());
          onChanged();
        } else {
          rowsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
       */
      public Builder addAllRows(
          java.lang.Iterable<? extends com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow> values) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, rows_);
          onChanged();
        } else {
          rowsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
       */
      public Builder clearRows() {
        if (rowsBuilder_ == null) {
          rows_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          rowsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
       */
      public Builder removeRows(int index) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          rows_.remove(index);
          onChanged();
        } else {
          rowsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
       */
      public com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow.Builder getRowsBuilder(
          int index) {
        return getRowsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
       */
      public com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRowOrBuilder getRowsOrBuilder(
          int index) {
        if (rowsBuilder_ == null) {
          return rows_.get(index);  } else {
          return rowsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
       */
      public java.util.List<? extends com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRowOrBuilder> 
           getRowsOrBuilderList() {
        if (rowsBuilder_ != null) {
          return rowsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(rows_);
        }
      }
      /**
       * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
       */
      public com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow.Builder addRowsBuilder() {
        return getRowsFieldBuilder().addBuilder(
            com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow.getDefaultInstance());
      }
      /**
       * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
       */
      public com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow.Builder addRowsBuilder(
          int index) {
        return getRowsFieldBuilder().addBuilder(
            index, com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow.getDefaultInstance());
      }
      /**
       * <code>repeated .com.ilmservice.personalbudget.SpreadsheetRow rows = 4;</code>
       */
      public java.util.List<com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow.Builder> 
           getRowsBuilderList() {
        return getRowsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow, com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow.Builder, com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRowOrBuilder> 
          getRowsFieldBuilder() {
        if (rowsBuilder_ == null) {
          rowsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow, com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow.Builder, com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRowOrBuilder>(
                  rows_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          rows_ = null;
        }
        return rowsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.ilmservice.personalbudget.UploadSpreadsheetEvent)
    }

    static {
      defaultInstance = new UploadSpreadsheetEvent(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.ilmservice.personalbudget.UploadSpreadsheetEvent)
  }

  public interface SpreadsheetRowOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ilmservice.personalbudget.SpreadsheetRow)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string fields = 1;</code>
     */
    com.google.protobuf.ProtocolStringList
        getFieldsList();
    /**
     * <code>repeated string fields = 1;</code>
     */
    int getFieldsCount();
    /**
     * <code>repeated string fields = 1;</code>
     */
    java.lang.String getFields(int index);
    /**
     * <code>repeated string fields = 1;</code>
     */
    com.google.protobuf.ByteString
        getFieldsBytes(int index);
  }
  /**
   * Protobuf type {@code com.ilmservice.personalbudget.SpreadsheetRow}
   */
  public static final class SpreadsheetRow extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.ilmservice.personalbudget.SpreadsheetRow)
      SpreadsheetRowOrBuilder {
    // Use SpreadsheetRow.newBuilder() to construct.
    private SpreadsheetRow(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SpreadsheetRow(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SpreadsheetRow defaultInstance;
    public static SpreadsheetRow getDefaultInstance() {
      return defaultInstance;
    }

    public SpreadsheetRow getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SpreadsheetRow(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                fields_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              fields_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          fields_ = fields_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ilmservice.personalbudget.protobufs.Events.internal_static_com_ilmservice_personalbudget_SpreadsheetRow_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ilmservice.personalbudget.protobufs.Events.internal_static_com_ilmservice_personalbudget_SpreadsheetRow_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow.class, com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow.Builder.class);
    }

    public static com.google.protobuf.Parser<SpreadsheetRow> PARSER =
        new com.google.protobuf.AbstractParser<SpreadsheetRow>() {
      public SpreadsheetRow parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SpreadsheetRow(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SpreadsheetRow> getParserForType() {
      return PARSER;
    }

    public static final int FIELDS_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList fields_;
    /**
     * <code>repeated string fields = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getFieldsList() {
      return fields_;
    }
    /**
     * <code>repeated string fields = 1;</code>
     */
    public int getFieldsCount() {
      return fields_.size();
    }
    /**
     * <code>repeated string fields = 1;</code>
     */
    public java.lang.String getFields(int index) {
      return fields_.get(index);
    }
    /**
     * <code>repeated string fields = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFieldsBytes(int index) {
      return fields_.getByteString(index);
    }

    private void initFields() {
      fields_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < fields_.size(); i++) {
        output.writeBytes(1, fields_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < fields_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(fields_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getFieldsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ilmservice.personalbudget.SpreadsheetRow}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ilmservice.personalbudget.SpreadsheetRow)
        com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRowOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ilmservice.personalbudget.protobufs.Events.internal_static_com_ilmservice_personalbudget_SpreadsheetRow_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ilmservice.personalbudget.protobufs.Events.internal_static_com_ilmservice_personalbudget_SpreadsheetRow_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow.class, com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow.Builder.class);
      }

      // Construct using com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        fields_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ilmservice.personalbudget.protobufs.Events.internal_static_com_ilmservice_personalbudget_SpreadsheetRow_descriptor;
      }

      public com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow getDefaultInstanceForType() {
        return com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow.getDefaultInstance();
      }

      public com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow build() {
        com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow buildPartial() {
        com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow result = new com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          fields_ = fields_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.fields_ = fields_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow) {
          return mergeFrom((com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow other) {
        if (other == com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow.getDefaultInstance()) return this;
        if (!other.fields_.isEmpty()) {
          if (fields_.isEmpty()) {
            fields_ = other.fields_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureFieldsIsMutable();
            fields_.addAll(other.fields_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ilmservice.personalbudget.protobufs.Events.SpreadsheetRow) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList fields_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureFieldsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          fields_ = new com.google.protobuf.LazyStringArrayList(fields_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string fields = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getFieldsList() {
        return fields_.getUnmodifiableView();
      }
      /**
       * <code>repeated string fields = 1;</code>
       */
      public int getFieldsCount() {
        return fields_.size();
      }
      /**
       * <code>repeated string fields = 1;</code>
       */
      public java.lang.String getFields(int index) {
        return fields_.get(index);
      }
      /**
       * <code>repeated string fields = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFieldsBytes(int index) {
        return fields_.getByteString(index);
      }
      /**
       * <code>repeated string fields = 1;</code>
       */
      public Builder setFields(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFieldsIsMutable();
        fields_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string fields = 1;</code>
       */
      public Builder addFields(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFieldsIsMutable();
        fields_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string fields = 1;</code>
       */
      public Builder addAllFields(
          java.lang.Iterable<java.lang.String> values) {
        ensureFieldsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, fields_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string fields = 1;</code>
       */
      public Builder clearFields() {
        fields_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string fields = 1;</code>
       */
      public Builder addFieldsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFieldsIsMutable();
        fields_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.ilmservice.personalbudget.SpreadsheetRow)
    }

    static {
      defaultInstance = new SpreadsheetRow(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.ilmservice.personalbudget.SpreadsheetRow)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ilmservice_personalbudget_UploadSpreadsheetEvent_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_ilmservice_personalbudget_UploadSpreadsheetEvent_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ilmservice_personalbudget_SpreadsheetRow_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_ilmservice_personalbudget_SpreadsheetRow_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Events.proto\022\035com.ilmservice.personalb" +
      "udget\"\212\001\n\026UploadSpreadsheetEvent\022\016\n\006user" +
      "Id\030\001 \001(\r\022\021\n\ttimestamp\030\002 \001(\003\022\020\n\010filename\030" +
      "\003 \001(\t\022;\n\004rows\030\004 \003(\0132-.com.ilmservice.per" +
      "sonalbudget.SpreadsheetRow\" \n\016Spreadshee" +
      "tRow\022\016\n\006fields\030\001 \003(\tB)\n\'com.ilmservice.p" +
      "ersonalbudget.protobufs"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_ilmservice_personalbudget_UploadSpreadsheetEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ilmservice_personalbudget_UploadSpreadsheetEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_ilmservice_personalbudget_UploadSpreadsheetEvent_descriptor,
        new java.lang.String[] { "UserId", "Timestamp", "Filename", "Rows", });
    internal_static_com_ilmservice_personalbudget_SpreadsheetRow_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ilmservice_personalbudget_SpreadsheetRow_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_ilmservice_personalbudget_SpreadsheetRow_descriptor,
        new java.lang.String[] { "Fields", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
